// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfxzuyD8D6-Sbog6DH225vTm1oXrZ90c0',
    appId: '1:43029763573:web:f2d5ef989a86fcf7667cbc',
    messagingSenderId: '43029763573',
    projectId: 'flutterapp-74583',
    authDomain: 'flutterapp-74583.firebaseapp.com',
    storageBucket: 'flutterapp-74583.appspot.com',
    measurementId: 'G-66GRJ1R673',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWqbR4tSYE3xe38LmYG5zXBuHCsXyia7c',
    appId: '1:43029763573:android:186371205bd1fecb667cbc',
    messagingSenderId: '43029763573',
    projectId: 'flutterapp-74583',
    storageBucket: 'flutterapp-74583.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvVVI4Zhxya2SJ0vhkqZG4yf87PYLEwa4',
    appId: '1:43029763573:ios:ccb6ed9bf2f53f67667cbc',
    messagingSenderId: '43029763573',
    projectId: 'flutterapp-74583',
    storageBucket: 'flutterapp-74583.appspot.com',
    iosClientId: '43029763573-rn6iajln1k4nobjjcf184upmd4icmk38.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvVVI4Zhxya2SJ0vhkqZG4yf87PYLEwa4',
    appId: '1:43029763573:ios:ccb6ed9bf2f53f67667cbc',
    messagingSenderId: '43029763573',
    projectId: 'flutterapp-74583',
    storageBucket: 'flutterapp-74583.appspot.com',
    iosClientId: '43029763573-rn6iajln1k4nobjjcf184upmd4icmk38.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication2',
  );
}
